### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by Jakob-Unfried**

### CODE REVIEW

**Comment by Jakob-Unfried** [comment]
- [ ] Documentation / readme

**Comment by Jakob-Unfried** [comment]
I pasted a minimal version of the git hooks into the docs.
I do not want to have my convenience checks for `FIXME` strings and breakpoints in the repo, because
then they will trigger on their own copy...

If you want to use my full scripts, find them pasted in #14

**Comment by jhauschild** [comment]
@Jakob-Unfried what's the ggrep command that you have in the example push?

**Comment by Jakob-Unfried** [comment]
> @Jakob-Unfried what's the ggrep command that you have in the example pre-commit?

Ah right. This is a mac os specific thing.
It is plain old GNU `grep`, the [brew installer](https://formulae.brew.sh/formula/grep) creates an alias as `ggrep` so it doesnt shadow the mac os builtin `grep`.

On Linux, just remove the extra `g` and use `grep`.

**Comment by Jakob-Unfried** [comment]
@jhauschild fixed in both the repo docs and in #14.

**Pull request merged**
